---
title: "DSCI602_M3Lab_Monte_Carlo_Cody_York"
author: "Cody York"
date: "2022-09-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Toss a Coin Until k Consecutive Heads

```{r}

# Create the functions
# The below toss() function will simulate tossing the coin and getting 
# conecutive heads which I have set heads as a 1 in the code. 
toss <- function(tosses, heads) {
  consech <- 0
  for (x in 1:tosses) {
      toss <- sample(0:1, 1, replace=TRUE)
      if (toss == 1) 
        consech <- consech + 1
      if (consech == heads) {
        return(1)
        break
      }
  }
  return(0)
}

# The below ngtm() function will run the Monte Carlo Simulation for m tosses,
# k consecutive heads and nreps number of reps. After the replicate function,
# I am left with a list so I did the reduce by adding function of R to get my 
# total. Then I return the probability by taking the count/nreps and subtracting 
# it from 1. 
ngtm <- function(m, k, nreps) {
  count <- replicate(nreps, toss(m, k))
  count <- Reduce('+', count)
  return(1-(count/nreps))
}

# The below will call the function and return the probability for 3 consecutive
# heads in 5 coin tosses.
ngtm(5,3,2000)

```
