---
title: "DSCI_602_Project1_Cody_York"
author: "Cody York"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the Age Data and Libraries

```{r}
library(readr)
library(tidyverse)
library(dslabs)
library(ggplot2)
library(dplyr)
library(scales)
library(DescTools) 

family_age_data <- read_csv("family_age_data.csv")
View(family_age_data)
```

## Histogram of All Ages

```{r}

age <- family_age_data$age

hist(age, col = c("Orange", "Blue"), ylim = c(0, 15), xlab = "Ages in Family",        main = "Histogram of All Ages in My Family Age Data", border = "Black")

```

## Histogram of Age of Genders

```{r}

gender <- factor(family_age_data$gender)

plot(gender, age, type = "h", 
     main = "Histogram of All Ages in My Family Age Data By Gender",
     xlab = "Ages in Family By Gender",
     ylab = "Ages",
     col = c("Pink", "Blue"))
```

## Pie Chart with Percentage of Family in Each Age Group

```{r}

counts_by_group <- family_age_data %>% group_by(category) %>%
                        count(category)

counts <- counts_by_group$n

proportion_of_counts <- family_age_data %>% group_by(category) %>%                                       arrange(desc(age)) %>%
                        mutate(prop = percent(age /sum(age)))

labels <- proportion_of_counts$prop

legend_values <- counts_by_group$category

pie(counts, labels, main = "Pie Chart of Counts of Each Age Category",
    col = heat.colors(length(counts)))
legend("topright", legend_values, fill = heat.colors(length(counts)) )

```

## Graph Statistical Values for All Ages

```{r}
all_data_mean <- mean(age)
all_data_median <- median(age)
all_data_mode <- Mode(age)
all_data_stats <- c(all_data_mean, all_data_median, all_data_mode)
all_data_percentiles <- quantile(age, probs= c(.25,.5,.75))

plot(all_data_percentiles, ylim = c(0, 100), type = "p", 
     main = "Quartiles of All Ages in My Family",
     xlab = "Statistics",
     ylab = "Ages",
     pch = 18,
     col = "red")

text(all_data_percentiles, 
     labels = c("25%", "50%", "75%"), 
     cex = 0.7, pos = 3, col = "black")


plot(all_data_stats, ylim = c(0, 40), type = "p",
     main = "Mean, Median and Mode of All Ages in My Family",
     xlab = "Statistics",
     ylab = "Ages",
     pch = 18,
     col = "blue")

text(all_data_stats, 
     labels = c("Mean", "Median", "Mode"), 
     cex = 0.7, pos = 3, col = "black")

```

## Graph Statistical Values for Males

```{r}
male_data <- family_age_data %>% filter(family_age_data$gender == 'm')
male_age <- male_data$age
male_data_mean <- mean(male_age)
male_data_median <- median(male_age)
male_data_mode <- Mode(male_age)
male_data_stats <- c(male_data_mean, male_data_median, 1)
male_data_percentiles <- quantile(age, probs= c(.25,.5,.75))

plot(male_data_percentiles, ylim = c(0, 100), type = "p", 
     main = "Quartiles of Male Ages in My Family",
     xlab = "Statistics",
     ylab = "Ages",
     pch = 18,
     col = "red")

text(male_data_percentiles, 
     labels = c("25%", "50%", "75%"), 
     cex = 0.7, pos = 3, col = "black")


plot(male_data_stats, ylim = c(0, 40), type = "p",
     main = "Mean, Median and Mode of Male Ages in My Family",
     xlab = "Statistics",
     ylab = "Ages",
     pch = 18,
     col = "blue")

text(male_data_stats, 
     labels = c("Mean", "Median", "Mode"), 
     cex = 0.7, pos = 3, col = "black")

```

## Graph Statistical Values for Females

```{r}
female_data <- family_age_data %>% filter(family_age_data$gender == 'f')
female_age <- female_data$age
female_data_mean <- mean(female_age)
female_data_median <- median(female_age)
female_data_mode <- Mode(female_age)
female_data_stats <- c(female_data_mean, female_data_median, female_data_mode)
female_data_percentiles <- quantile(age, probs= c(.25,.5,.75))

plot(female_data_percentiles, ylim = c(0, 100), type = "p", 
     main = "Quartiles of Female Ages in My Family",
     xlab = "Statistics",
     ylab = "Ages",
     pch = 18,
     col = "red")

text(female_data_percentiles, 
     labels = c("25%", "50%", "75%"), 
     cex = 0.7, pos = 3, col = "black")


plot(female_data_stats, ylim = c(0, 40), type = "p",
     main = "Mean, Median and Mode of Female Ages in My Family",
     xlab = "Statistics",
     ylab = "Ages",
     pch = 18,
     col = "blue")

text(female_data_stats, 
     labels = c("Mean", "Median", "Mode"), 
     cex = 0.7, pos = 3, col = "black")

```


## Three Group Boxplolt for all Data

```{r}
all_data_frame <- data.frame(all <- c(all_data_stats,
                                      all_data_percentiles),
                             males <- c(male_data_stats,
                                        male_data_percentiles),
                             females <- c(female_data_stats,
                                          female_data_percentiles))

boxplot(all_data_frame, ylim = c(0, 100), names = c("All", "Males", "Females"),
        ylab = "Age",
        main = "Three Box Plot for All, Male and Female Age Data",
        col = c("Grey", "Blue", "Pink"))


```